### your site title here

title: Cheer Han
description: 一个在试图做有人用产品的PM。

baseurl: "/another-theme" #name of GitHub repository
url: "https://cheerhan.github.io" #custom url to be used instead of GitHub repository
email: #


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
instagram: "hanjlm"
weibo: "cheer1124"
# twitter: "#"
# linkedin: "#"
# github: "#"
# researchgate: "#"
# orcid: "#"

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/
  data_projects:
    output: true
    permalink: /projects/data/:path/ 
  product_projects:
    output: true
    permalink: /projects/product/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
